version: 2
models:
  - name: stg_clean_data
    columns:
      - name: InvoiceNo
        tests:
          - not_null
      - name: CustomerID
        tests:
          - unique
          - not_null
      - name: Quantity
        tests:
          - not_null
      - name: UnitPrice
        tests:
          - not_null
      - name: InvoiceDate
        tests:
          - not_null
      - name: StockCode
        tests:
          - not_null